// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpSUlu4WTZ0fRtFDEYD5tYKi-tlqw-VQ8',
    appId: '1:515730982862:web:7771e86cccbcd58afc4d9f',
    messagingSenderId: '515730982862',
    projectId: 'my-app-wecode',
    authDomain: 'my-app-wecode.firebaseapp.com',
    storageBucket: 'my-app-wecode.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2uJ6nkYP1IXzVLvvsngs80lxVKRh0qo',
    appId: '1:515730982862:android:a476573896149d8efc4d9f',
    messagingSenderId: '515730982862',
    projectId: 'my-app-wecode',
    storageBucket: 'my-app-wecode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsSJ1eOBJWWdWjZpnpSwKytIK3VwrQ40w',
    appId: '1:515730982862:ios:d238e0a892cad648fc4d9f',
    messagingSenderId: '515730982862',
    projectId: 'my-app-wecode',
    storageBucket: 'my-app-wecode.appspot.com',
    iosClientId: '515730982862-shu0aielmsok4lhm05dhehmophubr2fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsSJ1eOBJWWdWjZpnpSwKytIK3VwrQ40w',
    appId: '1:515730982862:ios:d238e0a892cad648fc4d9f',
    messagingSenderId: '515730982862',
    projectId: 'my-app-wecode',
    storageBucket: 'my-app-wecode.appspot.com',
    iosClientId: '515730982862-shu0aielmsok4lhm05dhehmophubr2fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
